- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/RoslynTestFramework/AnalysisTestFixture.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/RoslynTestFramework/TestHelpers.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Framework/BuildWithTheHighestWarningLevelSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Framework/BuildWithTheHighestWarningLevelAnalyzer.cs
> Added analyzer for AV2210

- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Naming/DoNotIncludeContainingTypeNameInMembersSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.csproj
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/HelpLinkUris.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Naming/DoNotIncludeContainingTypeNameInMembersAnalyzer.cs
> Added analyzer for AV1710

- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Maintainability/AvoidBooleanParametersSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Maintainability/AvoidBooleanParametersAnalyzer.cs
> Added analyzer for AV1564.

- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Framework/FavorAsyncAwaitOverTaskContinueWithSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/AnalysisUtilities.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.csproj
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Framework/FavorAsyncAwaitOverTaskContinueWithAnalyzer.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Maintainability/AvoidExplicitBooleanComparisonsAnalyzer.cs
> Added analyzer for AV2235.

- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Maintainability/AvoidUsingNamedArgumentsSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/AnalysisUtilities.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Maintainability/AvoidBooleanParametersAnalyzer.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Maintainability/AvoidUsingNamedArgumentsAnalyzer.cs
> Added analyzer for AV1555.

- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/ClassDesign/TypesShouldHaveASinglePurposeSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/ClassDesign/TypesShouldHaveASinglePurposeAnalyzer.cs
> Added analyzer for AV1000.

- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/ClassDesign/MembersShouldDoASingleThingSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/AnalysisUtilities.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/ClassDesign/MembersShouldDoASingleThingAnalyzer.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/ClassDesign/TypesShouldHaveASinglePurposeAnalyzer.cs
> Added analyzer for AV1115.

- docs/Overview.md
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/MiscellaneousDesign/DoNotPassNullsOnEventInvocationSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/MiscellaneousDesign/DoNotPassNullsOnEventInvocationAnalyzer.cs
> Added analysis for AV1235.

- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Maintainability/SwitchStatementsShouldHaveADefaultCaseSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/AnalysisUtilities.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Maintainability/SwitchStatementsShouldHaveADefaultCaseAnalyzer.cs
> Added analyzer for AV1536.

- docs/Overview.md
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Naming/AvoidMisleadingNamesSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/AnalysisUtilities.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Maintainability/AvoidBooleanParametersAnalyzer.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Naming/AvoidMisleadingNamesAnalyzer.cs
> Added analyzer for AV1712.

- docs/Overview.md
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/MiscellaneousDesign/EvaluateQueriesBeforeReturningThemSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/AnalysisUtilities.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Maintainability/AvoidMembersWithMoreThanSevenStatementsAnalyzer.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/MiscellaneousDesign/EvaluateQueriesBeforeReturningThemAnalyzer.cs
> Added analyzer for AV1250.

- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/MiscellaneousDesign/EvaluateQueriesBeforeReturningThemSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/MiscellaneousDesign/EvaluateQueriesBeforeReturningThemAnalyzer.cs
Related to #9.
Correctness:
- skip all return types other than IEnumerable and IEnumerable<T>
Extra tests:
- updated testset for usage of redundant braces
- added test for `?.` (null conditional access operator)
- added test for `??` (null coalescing operator)
- added test for `new` array operator
- added test for `new` object operator
- added tests for variable/parameter/field/property assignment in return
statement
- added test for `default`
- added test for cast operator
- added tests for `yield return`
> Correctness and tests

- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/MiscellaneousDesign/EvaluateQueriesBeforeReturningThemSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/MiscellaneousDesign/EvaluateQueriesBeforeReturningThemAnalyzer.cs
Related to #9.
The analyzer for AV1250 now caches the evaluated state of variables, so they can be reused between multiple return statements within the same method.
This speeds up analysis of methods with multiple returns.
For example:
```csharp
IEnumerable<int> M(IList<int> source, bool flag)
{
var result1 = Enumerable.Empty<int>();
result1 = source.Select(x => x);
var result2 = result1;
var result3 = result2;
if (flag)
{
return result2;
}
else
{
return result3;
}
}
```
In this example, analysis for `result3` reuses the cached evaluation state of `result2`, so it does not need to re-evaluate the `result1` declaration and assignment.
> Performance optimization for methods with multiple returns

- docs/Overview.md
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Framework/OnlyUseDynamicForUnknownTypesSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Framework/OnlyUseDynamicForUnknownTypesAnalyzer.cs
> Added analyzer for AV2230.

- docs/Overview.md
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Naming/NameAsyncMethodsCorrectlySpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Naming/NameAsyncMethodsCorrectlyAnalyzer.cs
> Added analyzer for AV1755.

- docs/Overview.md
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Naming/DoNotUseHelperMethodsSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/AnalysisUtilities.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/ClassDesign/MembersShouldDoASingleThingAnalyzer.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/ClassDesign/TypesShouldHaveASinglePurposeAnalyzer.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Naming/DoNotUseHelperMethodsAnalyzer.cs
> Added analyzer for AV1708.

- docs/Overview.md
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Maintainability/CaseClausesInSwitchStatementsShouldHaveBracesSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Maintainability/CaseClausesInSwitchStatementsShouldHaveBracesAnalyzer.cs
> Added analyzer for AV1535.

- docs/Overview.md
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/MemberDesign/ReturnInterfacesToCollectionsSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/MemberDesign/ReturnInterfacesToCollectionsAnalyzer.cs
> Added analyzer for AV1130.

- docs/Overview.md
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Maintainability/AvoidNestedLoopsSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Maintainability/AvoidNestedLoopsAnalyzer.cs
> Added analyzer for AV1532.

- docs/Overview.md
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Maintainability/DoNotChangeLoopVariablesSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Maintainability/DoNotChangeLoopVariablesAnalyzer.cs
> Added analyzer for AV1530.

- docs/Overview.md
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Documentation/AvoidInlineCommentsSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Documentation/AvoidInlineCommentsAnalyzer.cs
> Added analyzer for AV2310.

- docs/Overview.md
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Maintainability/NamespacesShouldMatchAssemblyNameSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Maintainability/NamespacesShouldMatchAssemblyNameAnalyzer.cs
> Added analyzer for AV1505.

- docs/Overview.md
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Maintainability/AvoidConditionsWithDoubleNegativesSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/AnalysisUtilities.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.csproj
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Framework/OnlyUseDynamicForUnknownTypesAnalyzer.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/IdentifierInfo.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Maintainability/AssignVariablesInSeparateStatementsAnalyzer.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Maintainability/AvoidConditionsWithDoubleNegativesAnalyzer.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Maintainability/SwitchStatementsShouldHaveADefaultCaseAnalyzer.cs
> Added analyzer for AV1502.

- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Maintainability/NamespacesShouldMatchAssemblyNameSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Maintainability/NamespacesShouldMatchAssemblyNameAnalyzer.cs
Better handling of Core assemblies:
- Never allow types in global namespace
- Require that types are always defined in matching namespace, after extracting the Core suffix. For example, assembly 'Company.Product.Core' must warn on type 'Demo.Other.MyClass' but be silent on 'Company.Product.Feature.MyClass'.
Added exception for 'JetBrains.Annotations' namespace, because Resharper puts its annotation attributes there, if you choose to embed them in source code.
> Better handling of Core assemblies

- docs/Overview.md
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/CSharpGuidelinesAnalyzer.Test.csproj
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/ClassDesign/AvoidStaticClassesSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Naming/StaticClassesShouldOnlyContainExtensionMethodsSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/AnalysisUtilities.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.csproj
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/ClassDesign/AvoidStaticClassesAnalyzer.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Naming/StaticClassesShouldOnlyContainExtensionMethodsAnalyzer.cs
> Added analyzers for AV1008 and AV1745.

- docs/Overview.md
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Naming/DoNotUseNumbersInIdentifiersSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/AnalysisUtilities.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Maintainability/AvoidBooleanParametersAnalyzer.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Naming/DoNotUseNumbersInIdentifiersAnalyzer.cs
> Added analyzer for AV1704.

- docs/Overview.md
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Maintainability/DoNotAssignToParametersSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Maintainability/DoNotAssignToParametersAnalyzer.cs
> Added analyzer for AV1568.

- docs/Overview.md
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Maintainability/DoNotAssignToParametersSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Maintainability/OverloadsShouldCallOtherOverloadsSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/AnalysisUtilities.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Maintainability/DoNotAssignToParametersAnalyzer.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Maintainability/OverloadsShouldCallOtherOverloadsAnalyzer.cs
> Added analyzer for AV1551.

- docs/Overview.md
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Naming/DoNotUseAbbreviationsInIdentifierNamesSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Naming/DoNotUseNumbersInIdentifiersSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/AnalysisUtilities.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/ClassDesign/DoNotHideInheritedMembersAnalyzer.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/ClassDesign/MembersShouldDoASingleThingAnalyzer.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/ClassDesign/TypesShouldHaveASinglePurposeAnalyzer.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Maintainability/AvoidConditionsWithDoubleNegativesAnalyzer.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Naming/DoNotIncludeContainingTypeNameInMembersAnalyzer.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Naming/DoNotUseAbbreviationsInIdentifierNamesAnalyzer.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Naming/DoNotUseHelperMethodsAnalyzer.cs
> Added analyzer for AV1706.

- docs/Overview.md
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Naming/NamePropertiesWithAnAffirmativePhraseSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/AnalysisUtilities.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Naming/NamePropertiesWithAnAffirmativePhraseAnalyzer.cs
> Added analyzer for AV1715.

- docs/Overview.md
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Maintainability/AvoidMultipleTypesPerFileSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Maintainability/AvoidMultipleTypesPerFileAnalyzer.cs
> Added analyzer for AV1507.

- docs/Overview.md
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Naming/PrefixEventHandlersWithOnSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Naming/PrefixEventHandlersWithOnAnalyzer.cs
> Added analyzer for AV1738.

- docs/Overview.md
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/RoslynTestFramework/AnalysisTestFixture.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Framework/ProvideAssemblyInformationSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Framework/ProvideAssemblyInformationAnalyzer.cs
> Added analyzer for AV2215.

- docs/Overview.md
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Documentation/AvoidToDoCommentsSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Documentation/AvoidToDoCommentsAnalyzer.cs
> Added analyzer for AV2318.

- docs/Overview.md
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/RoslynTestFramework/AnalysisTestFixture.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Maintainability/IfElseIfStatementsShouldFinishWithElseClauseSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Maintainability/IfElseIfStatementsShouldFinishWithElseClauseAnalyzer.cs
> Added analyzer for AV1537.

- docs/Overview.md
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Naming/UseUnderscoresForUnusedLambdaParametersSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Naming/DoNotUseAbbreviationsInIdentifierNamesAnalyzer.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Naming/UseUnderscoresForUnusedLambdaParametersAnalyzer.cs
> Added analyzer for AV1739.

- docs/Overview.md
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Documentation/DocumentAllInternalMembersSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Documentation/DocumentAllInternalMembersAnalyzer.cs
> Added analyzer for AV2305.

- README.md
- docs/Configuration.md
- docs/Overview.md
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Maintainability/AvoidMemberWithManyStatementsSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Maintainability/AvoidSignatureWithManyParametersSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/TestDataBuilders/AnalyzerSettingsBuilder.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/TestDataBuilders/SourceCodeBuilderExtensions.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Rules/Maintainability/AvoidMemberWithManyStatementsAnalyzer.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Rules/Maintainability/AvoidSignatureWithManyParametersAnalyzer.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Settings/AnalyzerSettingKey.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Settings/AnalyzerSettingsProvider.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Settings/AnalyzerSettingsRegistry.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Settings/AnalyzerSettingsXmlConverter.cs
Currently implemented settings:
- AV1500: MaxStatementCount (0-255)
- AV1561: MaxParameterCount (0-255)
Fixes #108 (for the most part).
> Added support for rule configuration settings

- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Naming/SuffixAsyncMethodCorrectlySpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Extensions/SymbolExtensions.cs
Fixes #117 by recognizing parameterized test methods
> Adds detection of parameterized test methods

- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/ClassDesign/AvoidStaticClassSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Rules/ClassDesign/AvoidStaticClassAnalyzer.cs
> Adds exception for platform invoke wrappers to AV1008

- docs/Overview.md
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Framework/BuildWithTheHighestWarningLevelSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Rules/Framework/BuildWithTheHighestWarningLevelAnalyzer.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Rules/Framework/FavorAsyncAwaitOverTaskContinuationAnalyzer.cs
- src/Directory.Build.props
> Updated AV2210 to require warning level 9999

- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Maintainability/DoNotUseOptionalParameterWithDefaultValueNullSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/KnownTypes.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Rules/Maintainability/DoNotUseOptionalParameterWithDefaultValueNullAnalyzer.cs
> Suppress AV1553 on [CallerArgumentExpression] usage

- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Framework/AvoidQuerySyntaxForSimpleExpressionSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Rules/Framework/AvoidQuerySyntaxForSimpleExpressionAnalyzer.cs
Redesign AV2220: only report when conversion to method syntax consists of a single invocation or when method syntax is easier to read.
Fixes #137.
> Redesign AV2220

- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer.Test/Specs/Naming/DoNotIncludeContainingTypeNameInMemberNameSpecs.cs
- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Rules/Naming/DoNotIncludeContainingTypeNameInMemberNameAnalyzer.cs
> AV1710: Add exception for User.UserName

- src/CSharpGuidelinesAnalyzer/CSharpGuidelinesAnalyzer/Rules/Naming/DoNotUseAbbreviationInIdentifierNameAnalyzer.cs
> Add "doc" to the blacklisted words

- CSharpGuidelines.Layer.DotSettings
> Update layer settings for Resharper/Rider v2024.1
